
require 'factor/connector/bitballoon'
require 'factor/connector/ftp'
require 'factor/connector/github'
require 'factor/connector/heroku'
require 'factor/connector/hipchat'
require 'factor/connector/pushover'
require 'factor/connector/ssh'
require 'factor/connector/timer'
require 'factor/connector/travis'
require 'factor/connector/web'